# Generated by Django 4.0.5 on 2022-06-16 18:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='id',
        ),
        migrations.AddField(
            model_name='reply',
            name='reply_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
