# Generated by Django 4.0.5 on 2022-06-16 10:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('body', djrichtextfield.models.RichTextField(max_length=10000)),
                ('image', models.ImageField(blank=True, upload_to='event_images')),
                ('e_time', models.DateTimeField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('going', models.ManyToManyField(related_name='going', to=settings.AUTH_USER_MODEL)),
                ('not_going', models.ManyToManyField(related_name='not_going', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
