# Generated by Django 4.0.5 on 2022-06-16 17:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0002_alter_event_options_remove_event_going_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='going',
            field=models.ManyToManyField(blank=True, related_name='going', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='event',
            name='not_going',
            field=models.ManyToManyField(blank=True, related_name='not_going', to=settings.AUTH_USER_MODEL),
        ),
    ]
