# Generated by Django 4.0.5 on 2022-06-17 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_event_going_event_not_going'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='not_going',
        ),
    ]
