# Generated by Django 4.0.5 on 2022-06-17 19:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0004_remove_event_not_going'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='going',
            field=models.ManyToManyField(blank=True, related_name='going_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='EventNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
