# Generated by Django 4.0.5 on 2022-06-18 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_going_eventnumbers'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fee',
            field=models.PositiveIntegerField(default=0, help_text=True),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(default=0, max_length=160),
        ),
    ]
