# Generated by Django 4.0.5 on 2022-06-18 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_remove_friend_followers_friend_followers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='friend',
            old_name='followers',
            new_name='following',
        ),
    ]
